gitext-rs/git-stack

src/git/repo.rs, tests/repo.rs
I noticed that after running `git-stack --pull`, my INDEX was set to an
old state.  I got the tests to reproduce this.  By adding force, it
seemed to go away.  It should be safe to force because we ensure the
tree is clean before doing anything.
=> fix(git): No dirty tree on branch switch

.github/workflows/post-release.yml, Cargo.lock, Cargo.toml, src/backup/backup.rs, src/backup/mod.rs, src/backup/stack.rs, src/bin/git-branch-backup/args.rs, src/bin/git-branch-backup/main.rs, src/bin/git-stack/args.rs, src/bin/git-stack/stack.rs, src/config.rs, src/lib.rs
=> feat(git): Backup before every rebase

src/bin/git-stack/stack.rs, src/git/repo.rs, src/graph/ops.rs, tests/fixture.rs
This reverts commit 892117bfc80f50d4170546829ad27920b7796bd6.
I think I misunderstood tree id
=> Revert "feat(graph): Support dropping commits/branches"

src/bin/git-stack/stack.rs, src/graph/node.rs
I finally did multiple protected branches and merging panics because I
didn't plan for all cases.  We should now be good.
=> fix(graph): Correctly merge disparaet trees

CHANGELOG.md, src/graph/actions.rs, src/graph/ops.rs
When redoing the scripting logic, I missed the case for the very first
commit and ended up stacking all the branches off of it.
=> fix(graph): Don't stack unrelated branches

CHANGELOG.md, src/graph/node.rs
We had a crash because we merged a history dating back to the beginning
into a branch.  This happens because the "pre-historic" branch was
actually a parent branch and we skipped the condition for the branch to
end, so we only terminate at end of iteration.
=> fix(graph): Panic on parent branch merge into child branch

CHANGELOG.md, src/bin/git-stack/stack.rs, src/graph/node.rs
When merging unique protected branch stacks when showing, we would
insert new commits *after* all protected commits are marked, causing us
to not mark the new ones as protected.
This propogates the protected status.
=> fix(graph): Allow merging after marking protected

src/bin/git-stack/stack.rs
- Protected branches blended into the commit message because they tended
to not have a branch status as a separator
- Color overload can reduce value of color, playing with reducing the
"hint" to not be as standout
=> fix(cli): Make colors stand out more

src/bin/git-stack/stack.rs
In my current color scheme, default colors are somewhat ... dimmed.
Trying out bold to see if it improves things generally.
Also, realized we should probably make it easier to read standard commit
messages, reducing color distinctions.
=> fix(cli): More color tweaks

src/bin/git-branch-stash/args.rs, src/bin/git-branch-stash/main.rs, src/bin/git-stack/stack.rs, src/config.rs, src/lib.rs, src/stash/mod.rs, src/stash/snapshot.rs, src/stash/stack.rs
This framing helps clarify how someone is intended to use the command,
which makes sense considering it was modeled after `git stash`.
=> fix!: Rename `git-branch-backup` to `git-branch-stash`

Cargo.lock, crates/git-fixture/Cargo.toml, crates/git-fixture/src/lib.rs, crates/git-fixture/src/main.rs, crates/git-fixture/src/model.rs, src/bin/git-stack/stack.rs, src/git/repo.rs, src/graph/ops.rs, tests/fixture.rs, tests/fixtures/git_rebase_existing.yml, tests/fixtures/git_rebase_new.yml, tests/fixtures/pr-semi-linear-merge.yml, tests/fixtures/pr-squash.yml, tests/repo.rs
Before, when doing a `git-stack --pull`, we'd rebase the merged branch
onto master.  `git` would the automatically detect the commit is merged
and drop it.  We'd then associate the branch name with the same commit
master points to and have to delete it manually.
This tries to detect that case so we can automatically delete the stale
branch on behalf of users.
This does not help if your branch is behind master because those extra
commits will impact how we are detecting this case (tree id).
This is a spiritual revert of 80f5158,
re-implementing 892117b to handle all
of our changes and with a little more experience and context.
This is a part of #28.
=> fix(graph): Gracefully handle squash-merges

README.md
Maybe they decided to drop support for the `/discussions/categories` page, on account of the feature being in beta?
=> Fix broken Discussions link in README.md

src/bin/git-branch-stash/args.rs, src/bin/git-branch-stash/main.rs, src/bin/git-stack/stack.rs, src/git/repo.rs
Known issues:
- Error cases will likely lead to leaving the user's state in the stash.
Future work
- Reduce the scope of stashing and detect when we can bypass it
- Config or command-line flags to control whether to stash
Fixes #62
=> feat(cli): Auto-stash

Cargo.lock, Cargo.toml, docs/reference.md, src/bin/git-stack/args.rs, src/bin/git-stack/stack.rs, src/config.rs, src/git/repo.rs, src/graph/ops.rs, tests/fixture.rs
This is a step towards #111.  For now, we are collapsing old branches
into a single item and still showing their merge-base.  We will not try
to rebase them or process fixups.
Unlike `-count`, we are not listing the names of those branches with a
message about the age because I'm assuming we'll soon get this to the
ideal state where we list these branches like we do empty stacks.
=> feat(graph): Avoid showing old branches

src/bin/git-stack/stack.rs, src/config.rs
Realized that we don't care about the remote's state except for what can
be pruned, so going ahead and limiting ourselves to just that.
=> perf(cli): Only prune remote dev branches

src/bin/git-stack/stack.rs, src/graph/mod.rs, src/graph/ops.rs
This fixes a bug with snapping and has a fairly safe merging of stacks previously split.
=> Further improve repair support

src/bin/git-stack/stack.rs, src/graph/ops.rs, tests/graph.rs
Before, we auto-protect all old branches or those from another user.  As
pointed out in #107, sometimes you want to ressurect or take over those
branches but `git-stack` doesn't support this.  You either have to
disable these features or use raw git commands.
Now, we will never auto-protect HEAD, allowing editing of it.
=> fix(cli): Do not auto-protect HEAD

src/bin/git-stack/stack.rs
When deciding what to prune, we use `git ls-remote` to see what is
present.  When parsing the output, instead of processing the individual
fields, I took the shortcut of `rsplit_once('/')` which returned the
incorrect name for `names/with/slashes`.
Now we parse it more correctly.
Fixes #161
=> fix(git): Don't prune valid remote branches

src/bin/git-stack/stack.rs
I overlooked this triple hitter when writing out the various stacking
cases.
This should fix the problem in
https://github.com/epage/git-stack/discussions/172
=> fix(stack): Don't panic on --base --onto --stack all

docs/design.md
The repository moved from https://github.com/epage/git-stack to https://github.com/gitext-rs/git-stack. For some reason, this link to a specific issue broke as a result, even though other links (such as to the general issue tracker page) seem to redirect correctly.
=> docs: Fix link

src/bin/git-stack/args.rs, src/bin/git-stack/main.rs
This helps when running outside of `git`.  Because of the limited case,
its hidden.
This supersedes #195
=> feat(cli): Support `-C`

Cargo.lock, Cargo.toml, src/bin/git-stack/stack.rs, src/git/branches.rs, src/git/repo.rs, src/graph/ops.rs
This is a step towards #194.  Using an unbounded revwalk that is topologically sorted is very expensive, once.
This removes most uses and speeds things up when there are no feature branches.  With only `master` on `gecko-dev`, we went from ~25s to <1s.  However, we still need to remove the last topoligical sort which is used for creating the commit graph, so generally people will not see a speed up yet.
However, we did improve the logic for picking protected bases as part of this.
=> perf: Remove a lot of uses of fully-sorted commit graph

src/bin/git-stack/stack.rs
=> fix(cli): Consistently space stacks

src/bin/git-stack/config.rs, src/bin/git-stack/stack.rs, src/git/branches.rs, src/git/repo.rs, tests/branches.rs
These will be hidden unless they diverge from the branches locally.
Cases where this would happen:
- You've done a manual fetch
- You've run `git branch-stash pop git-stack`
- You are developing on a protected branch (granted, we'll still mark it
as protected)
This also leads towards https://github.com/gitext-rs/git-stack/issues/12
=> feat(git): Include matching pull branches

src/bin/git-stack/stack.rs, src/graph/ops.rs
When tracking remotes for #12, we had a couple of regressions.
First, we might treat the local and remote branches as separate bases.  So instead we are switching to only protecting remote branches when a local branch is present.  This should implement the majority of #12's remaining work.
Second, we lost the tracking of the "pull range".  We
want to understand what commits were skipped when fast forwarding the
local base branch onto the remote.  We did this by having the local
branch be the base / protected.  We then compared the local `.id` to the
`.pull_id`.
By switching to protecting (and making the base) the remote branch,
`.id` and `.pull_id` became the same.  We could use `--base` and `--onto`
instead but they'll be the same in the default case.
So instead when we infer `--base` or …
=> fix(git): Issues from tracking remotes

src/bin/git-stack/stack.rs, src/graph/ops.rs
#211 and #212 built up support for #12 but there were some corner cases that weren't handled
- `main` was not being updated when pulling
- `main` showed as unprotected branch on a protected commit
- We weren't puling from the users selected remote
- We might push `main` which is good for a fork model but not for a central model
To address these, small tweaks were made that also streamline the code, making things more principled based which should hopefully make it clearer.
The downside is that we've gone back to `main` always being protected rather than allowing it to be unprotected and rebasing it.
=> fix: Handle repurcissions for remote support

src/bin/git-stack/stack.rs
After #207, we ended up with
```
8dc84dc net: phy: broadcom: Enable 10BaseT DAC early wake
├─┐
│ ⌽ slow (ready) slow
│
⌽ master (no remote) Revert "gpio: Revert regression in sysfs-gpio (gpiolib.c)"
⌽ 551acdc Merge tag 'net-5.17-final' of git://git.kernel.org/pub/scm/linux/kernel/git/netdev/net
├─┐
│ ⌽ linux-5.17.y (no remote) Linux 5.17
│ ⌽ wmo/linux-5.17.y-backports (no remote) net: dsa: mv88e6xxx: Fill in STU support for all supported chips
│ ⌽ wmo/linux-5.17.y (pushed) net: dsa: Backport Marvell Peridot cmode fix from Netbox
⌽ net-bridge-host-l2-multicast (no remote) selftests: forwarding: verify flood of known mc on mcast_router port
```
We were giving space after the first gap but not subsequent.  We needed
something more like a `join` operation.  Now we do.
=> fix(cli): Give space after each subtree

docs/reference.md, src/bin/git-stack/args.rs, src/bin/git-stack/stack.rs, src/config.rs, src/git/branches.rs, src/git/repo.rs
In https://github.com/gitext-rs/git-stack/discussions/216, a user is backporting changes on Linux and hadn't marked
protected branches which would serve as bases, causing git-stack to
topologically sort commits that are very distant from each other,
causing a simple showing of the commit graph to take 20-30s.
This change infers that these branches are do not belong to their base
and split them off.  Now showing the commit graph takes about 6s as it
tries each base.
=> perf(cli): Split off highly divergent branches

src/bin/git-stack/stack.rs
Before, we auto-protected and trimmed all foreign or old branches,
unless they are the HEAD.
Context-specific behavior though can be confusing (especially when
people are frequently pulling other people's branches for read-only
purposes like reviewing).
Now, we unconditionally protect all foreign branches.
- Old branches are a bit of a special case; they should be fine to
update if they are HEAD
- We still special case for trimming to provide context for the user.
Next steps
- Improve the workflow for taking over someone else's branch.  Right
now, it requires making a change outside of `git stack`
- Show protected commits on a foreign branch
Fixes #232
=> fix: Always protect foreign branches

src/git/branches.rs
In cargo, the release branch points to a parent commit of `master` and
`master` was being selected instead because we didn't prioritize shorter
distance.
iirc we do caching of commit counts, so this shouldn't slow us down.
=> fix: Identify parent branch with release branches

src/bin/git-stack/stack.rs, src/git/repo.rs
In #239, there was a panic from a git2 call that failed.  Rather than
mask it or bubble it up and ignore it, I'd like to get details so we can
see how we should handle errors like this.
=> fix: Add more panic details

src/git/branches.rs
If you are in this situation
- v3-master
- dev
- master
`v3-master` was being picked as the parent instead of `master` because `dev` was the merge base but we were ignoring that.
=> fix: Associate correct parent

src/bin/git-stack/run.rs, src/graph/mod.rs
If a command failed on a commit, we won't run the command on the descendant commits as they are likely to fail as well and someone is likely wanting to fix the first failure.
The default can be configured by changing the alias to include `--no-ff`.  A user can then override this with the hidden `--ff`.
Fixes #262
=> feat(run): Fail fast support

src/bin/git-stack/sync.rs
We were rebasing onto a stale upstream, requiring two `sync`s to do anything.
=> fix(sync): Rebase onto latest upstream

src/bin/git-stack/amend.rs, tests/testsuite/amend.rs, tests/testsuite/reword.rs
When amending a non-HEAD commit, we dropped all of the commits after it as we accidentally moved the branch to point to the fixup target.
=> fix(amend): Don't drop commits after target

src/bin/git-stack/amend.rs, src/bin/git-stack/next.rs, src/bin/git-stack/prev.rs, src/bin/git-stack/reword.rs, src/bin/git-stack/run.rs, src/git/repo.rs, tests/testsuite/reword.rs
- This clarifies the error message
- This reports it before performing side effects
- We report it for reword which we weren't doing before
- This fixes `is_dirty` checks for doing things like stashing
=> fix: Report in-progress error earlier 

src/bin/git-stack/stack.rs, src/legacy/graph/ops.rs
This fixes the panic from #303, exposing the other issue of branches getting messed up.  This fixes one aspect (rebasing `onto` onto `onto`).  This still leaves `main` being moved.
Fixes #303
=> fix(stack): Don't panic when `--onto <sha>`

CHANGELOG.md, src/bin/git-stack/stack.rs
For some reason, we ignored the branch we were supposed to show it for and only showed it for the first.
=> fix(stack): Show correct branch position

Cargo.lock, Cargo.toml
Without this, the `builder.format_timestamp_millis()` statement in `logger.rs` has no effect
=> fix: add humantime feature to env_logger

src/graph/mod.rs, src/graph/ops.rs
Repeatedly, the local master doesn't get moved.  This seems to fix it.
- We weren't checking for branches on the starting commit and sometimes we start on the new master
- When on a branch commit, we weren't correctly walking children because we were talking about "primary" when there isn't always a primary commit
I'm a bit unsure on that last one.  Hope this doesn't break more
=> fix(graph): Ensure local master moves to upstream

src/rewrite/mod.rs
We were losing the rewritten HEAD when a later batch of commands was
run.
=> fix(rewrite): Always use the original HEAD 
