gitext-rs/git-stack

Cargo.lock, Cargo.toml, src/config.rs
This aims to integrate with `git` and act like a first-class `git` command by supporting its way of reading config.
=> feat(config): Be a first-class git command

CHANGELOG.md, src/bin/git-stack/stack.rs
=> feat(cli): Highlight HEAD branch

src/bin/git-stack/stack.rs
This will ensure we report an accurate status for these branches,
including representing when they get deleted.  In using `git-stack`,
I've been finding I have a lot of lingering branches in my origin
remote.
=> feat(cli): Have pull also update unprotected branches

docs/comparison.md
As far as https://github.com/arxanas/git-branchless, the two projects don't appear to overlap, as far as I can tell. They do both provide undo features, though (in different capacities).
Updating all local branches is a definite goal which I hope to implement one day in the form of a `git sync` command: https://github.com/arxanas/git-branchless/discussions/48, or perhaps via implementing Mercurial revsets and writing `git move -s 'draft()' -d origin/master`.
=> `git-branchless` -> `git-branchstack`

README.md, docs/reference.md, src/bin/git-stack/args.rs, src/bin/git-stack/stack.rs, src/config.rs
Inspired by #102, this cleans up some of the flags and documents them.
=> Clarify intent of action flags

src/bin/git-stack/stack.rs
This will help reduce a lot of tree depth for people with a lot of
release branches hanging around.
This also removes the main cause of stackoverflow in #90 because we
won't be finding the common ancestor across all protected branches and
then having to recurse from that point to the leaf commits.  We still
have a problem when dealing with branches not marked as protected.
Fixes #113
=> fix(cli): Do not show protect-branch merge bases

src/config.rs
=> fix(config): Read commit-age from gitconfig

docs/comparison.md
@arxanas suggested at some point that I add my tool to this page. It's much larger in scope, but making it easier to work with stacks of commits is definitely one of the goals (especially the automatic rebasing after every command helps a lot, IMO).
=> docs(compare): add Jujutsu (jj) to list

Cargo.lock, Cargo.toml, src/bin/git-branch-stash/args.rs, src/bin/git-stack/args.rs, src/bin/git-stack/stack.rs, src/config.rs, src/log.rs
ie don't override a users current workflow with our defaults.
This came out of https://github.com/epage/git-stack/discussions/187
=> fix(git): Only set upstream on first-push

Cargo.toml, crates/git-fixture/src/main.rs, crates/git-fixture/src/model.rs, src/bin/git-stack/args.rs, src/bin/git-stack/stack.rs, src/config.rs, src/graph/node.rs, src/graph/ops.rs, src/stash/stack.rs
Inspired by https://github.com/epage/git-stack/discussions/189
=> feat(cli): List stacked branches 

src/git/repo.rs, src/graph/mod.rs, tests/graph.rs, tests/repo.rs
=> perf: Bound topological sorts

src/git/commands.rs, src/git/repo.rs
=> fix(git): Call git hooks

src/bin/git-stack/config.rs, src/bin/git-stack/stack.rs, src/git/branches.rs, src/git/repo.rs, src/graph/mod.rs, src/graph/ops.rs, tests/branches.rs, tests/fixture.rs, tests/repo.rs
It'll take some more work to support a base that isn't a branch.
This is part of #174
=> feat(git): Allow remote refs for --base/--onto

src/bin/git-stack/stack.rs
=> feat(git): Allow base/onto that is a commit

src/git/repo.rs
In the linux repo with a topic branch off of a very old commit, `git
stack` is taking around 18s.  This drops it to 12s.  We are doing a lot
of repeated merge-base calls as each level has its own version of the
question to ask.  At first, I was worried about the order of the
parameters limiting the value of the cache but we seem to be pretty
consistent in the order we provide them.
See #216
=> perf(git): Cache merge-bases in-memory

Cargo.lock, Cargo.toml, docs/reference.md, src/bin/git-stack/amend.rs, src/bin/git-stack/reword.rs, src/bin/git-stack/stack.rs, src/bin/git-stack/sync.rs, src/git/repo.rs, src/legacy/git/repo.rs
This is completely untested as I don't do signing and I'm unsure of a good test strategy for it.
Fixes #258
=> feat: gpgSign support

src/bin/git-stack/next.rs, src/bin/git-stack/ops.rs, src/bin/git-stack/prev.rs, src/bin/git-stack/run.rs
=> feat(run): Flag to jump to the first failed commit

src/bin/git-stack/ops.rs, src/bin/git-stack/sync.rs
=> fix(sync): Use the correct rebase base

src/bin/git-stack/run.rs
A trailing `success` might lead people to think everything worked when that is only referring to the last run.
=> fix(run): Clarify what is happening

src/bin/git-stack/amend.rs, src/bin/git-stack/ops.rs, tests/testsuite/amend.rs, tests/testsuite/reword.rs
This addresses several issues with amend
=> fix(amend): Be on fixup on failure plus others

src/bin/git-stack/alias.rs, tests/testsuite/alias.rs, tests/testsuite/main.rs
=> fix(alias): Auto-detect user config file

docs/comparison.md
This list is a great reference, so here's a couple more items!
=> comparison.md: add a couple more alternatives

README.md
Just found your project and I am super excited about it! I hope to be able to contribute more in the future, but this pr is simply for adding a bit of clarity on some of the getting started commands in the README. I found the wording a bit tricky (I'm not sure if that's just a me problem, I use lazygit so maybe I'm just a bit rusty :shrug:) but once I messed around a little bit with the available commands and options I think I understood better what the docs were trying to say. This commit is just a simple rewording and addition for some clarity. If you are happy to have documentation improvements like this one, I'd also be stoked to run through the documentation in the docs dir as I get more familiar with your project!
=> Update README FAQ section

Cargo.lock, Cargo.toml
=> chore: Update git2
